(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by psc-bundle 0.8.0.0
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Prelude

  //- Functor --------------------------------------------------------------------

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };

  //- Bounded --------------------------------------------------------------------

  exports.topInt = 2147483647;
  exports.bottomInt = -2147483648;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Prelude"];
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Bounded = function (bottom, top) {
      this.bottom = bottom;
      this.top = top;
  };            
  var top = function (dict) {
      return dict.top;
  };                  
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (dictApplicative) {
      return pure(dictApplicative);
  };
  var otherwise = true;
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (dictFunctor) {
      return map(dictFunctor);
  };
  var functorArray = new Functor($foreign.arrayMap);
  var boundedInt = new Bounded($foreign.bottomInt, $foreign.topInt);
  var bottom = function (dict) {
      return dict.bottom;
  };
  var bind = function (dict) {
      return dict.bind;
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (dictApply) {
      return apply(dictApply);
  };
  var liftA1 = function (dictApplicative) {
      return function (f) {
          return function (a) {
              return $less$times$greater(dictApplicative["__superclass_Prelude.Apply_0"]())(pure(dictApplicative)(f))(a);
          };
      };
  };
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return bind(dictMonad["__superclass_Prelude.Bind_1"]())(f)(function (v) {
                  return bind(dictMonad["__superclass_Prelude.Bind_1"]())(a)(function (v1) {
                      return $$return(dictMonad["__superclass_Prelude.Applicative_0"]())(v(v1));
                  });
              });
          };
      };
  };
  exports["Bounded"] = Bounded;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["bottom"] = bottom;
  exports["top"] = top;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["<*>"] = $less$times$greater;
  exports["apply"] = apply;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["otherwise"] = otherwise;
  exports["functorArray"] = functorArray;
  exports["boundedInt"] = boundedInt;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports, console */
  "use strict";

  exports.error = function (s) {
    return function () {
      console.error(s);
      return {};
    };
  };
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Console"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["error"] = $foreign.error;;
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff.Random

  exports.random = Math.random;
 
})(PS["Control.Monad.Eff.Random"] = PS["Control.Monad.Eff.Random"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Int

  exports.fromNumberImpl = function (just) {
    return function (nothing) {
      return function (n) {
        /* jshint bitwise: false */
        return (n | 0) === n ? just(n) : nothing;
      };
    };
  };

  exports.toNumber = function (n) {
    return n;
  };
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Maybe.Unsafe

  exports.unsafeThrow = function (msg) {
    throw new Error(msg);
  };
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.Maybe.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];     
  var fromJust = function (v) {
      if (v instanceof Data_Maybe.Just) {
          return v.value0;
      };
      if (v instanceof Data_Maybe.Nothing) {
          return $foreign.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");
      };
      throw new Error("Failed pattern match at Data.Maybe.Unsafe line 10, column 1 - line 11, column 1: " + [ v.constructor.name ]);
  };
  exports["fromJust"] = fromJust;;
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  /* global exports */
  "use strict";          

  exports.floor = Math.floor;
 
})(PS["Math"] = PS["Math"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Math"];
  exports["floor"] = $foreign.floor;;
 
})(PS["Math"] = PS["Math"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.Int"];
  var Prelude = PS["Prelude"];
  var Data_Int_Bits = PS["Data.Int.Bits"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var $$Math = PS["Math"];                                                                   
  var fromNumber = $foreign.fromNumberImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var unsafeClamp = function (x) {
      if (x >= $foreign.toNumber(Prelude.top(Prelude.boundedInt))) {
          return Prelude.top(Prelude.boundedInt);
      };
      if (x <= $foreign.toNumber(Prelude.bottom(Prelude.boundedInt))) {
          return Prelude.bottom(Prelude.boundedInt);
      };
      if (Prelude.otherwise) {
          return Data_Maybe_Unsafe.fromJust(fromNumber(x));
      };
      throw new Error("Failed pattern match at Data.Int line 48, column 1 - line 49, column 1: " + [ x.constructor.name ]);
  };
  var floor = function ($2) {
      return unsafeClamp($$Math.floor($2));
  };
  exports["floor"] = floor;
  exports["fromNumber"] = fromNumber;
  exports["toNumber"] = $foreign.toNumber;;
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Random"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Int = PS["Data.Int"];
  var randomInt = function (low) {
      return function (high) {
          return function __do() {
              var v = $foreign.random();
              var asNumber = ((Data_Int.toNumber(high) - Data_Int.toNumber(low)) + 1) * v + Data_Int.toNumber(low);
              return Data_Int.floor(asNumber);
          };
      };
  };
  exports["randomInt"] = randomInt;;
 
})(PS["Control.Monad.Eff.Random"] = PS["Control.Monad.Eff.Random"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  //------------------------------------------------------------------------------
  // Array size ------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.length = function (xs) {
    return xs.length;
  };

  //------------------------------------------------------------------------------
  // Extending arrays ------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.cons = function (e) {
    return function (l) {
      return [e].concat(l);
    };
  };

  exports.snoc = function (l) {
    return function (e) {
      var l1 = l.slice();
      l1.push(e);
      return l1;
    };
  };

  exports.concat = function (xss) {
    var result = [];
    for (var i = 0, l = xss.length; i < l; i++) {
      var xs = xss[i];
      for (var j = 0, m = xs.length; j < m; j++) {
        result.push(xs[j]);
      }
    }
    return result;
  };

  //------------------------------------------------------------------------------
  // Subarrays -------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.slice = function (s) {
    return function (e) {
      return function (l) {
        return l.slice(s, e);
      };
    };
  };
 
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.Array"];
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  exports["snoc"] = $foreign.snoc;
  exports["cons"] = $foreign.cons;
  exports["length"] = $foreign.length;;
 
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Array.Unsafe

  exports.unsafeIndex = function (xs) {
    return function (n) {
      return xs[n];
    };
  };
 
})(PS["Data.Array.Unsafe"] = PS["Data.Array.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.Array.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Array = PS["Data.Array"];
  exports["unsafeIndex"] = $foreign.unsafeIndex;;
 
})(PS["Data.Array.Unsafe"] = PS["Data.Array.Unsafe"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Utils

  exports.ensure3 = function (nothing) {
    return function (just) {
      return function (v) {
        if (v === undefined || v === null) {
          return nothing;
        } else {
          return just(v);
        }
      };
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Utils"] = PS["Data.DOM.Simple.Unsafe.Utils"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_Maybe = PS["Data.Maybe"];     
  var ensure = $foreign.ensure3(Data_Maybe.Nothing.value)(Data_Maybe.Just.create);
  exports["ensure"] = ensure;;
 
})(PS["Data.DOM.Simple.Unsafe.Utils"] = PS["Data.DOM.Simple.Unsafe.Utils"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Element

  exports.unsafeGetElementById = function (targId) {
    return function (src) {
      return function () {
        return src.getElementById(targId);
      };
    };
  };

  exports.unsafeGetElementsByClassName = function (targId) {
    return function (src) {
      return function () {
        return Array.prototype.slice.call(src.getElementsByClassName(targId));
      };
    };
  };

  exports.unsafeGetElementsByName = function (targId) {
    return function (src) {
      return function () {
        return Array.prototype.slice.call(src.getElementsByName(targId));
      };
    };
  };

  exports.unsafeQuerySelector = function (selector) {
    return function (src) {
      return function () {
        return src.querySelector(selector);
      };
    };
  };

  exports.unsafeQuerySelectorAll = function (selector) {
    return function (src) {
      return function () {
        return src.querySelectorAll(selector);
      };
    };
  };

  exports.unsafeGetAttribute = function (name) {
    return function (src) {
      return function () {
        return src.getAttribute(name);
      };
    };
  };

  exports.unsafeSetAttribute = function (name) {
    return function (value) {
      return function (src) {
        return function () {
          src.setAttribute(name, value);
          return {};
        };
      };
    };
  };

  exports.unsafeHasAttribute = function (name) {
    return function (src) {
      return function () {
        return src.hasAttribute(name);
      };
    };
  };

  exports.unsafeRemoveAttribute = function (name) {
    return function (src) {
      return function () {
        src.removeAttribute(name);
        return {};
      };
    };
  };

  exports.unsafeGetStyleAttr = function (name) {
    return function (src) {
      return function () {
        return src.style[name];
      };
    };
  };

  exports.unsafeSetStyleAttr = function (name) {
    return function (value) {
      return function (src) {
        return function () {
          src.style[name] = value;
          return {};
        };
      };
    };
  };

  exports.unsafeChildren = function (src) {
    return function () {
      return Array.prototype.slice.call(src.children);
    };
  };

  exports.unsafeAppendChild = function (src) {
    return function (child) {
      return function () {
        return src.appendChild(child);
      };
    };
  };

  exports.unsafeInnerHTML = function (src) {
    return function () {
      return src.innerHTML;
    };
  };

  exports.unsafeSetInnerHTML = function (value) {
    return function (src) {
      return function () {
        src.innerHTML = value;
        return {};
      };
    };
  };

  exports.unsafeTextContent = function (src) {
    return function () {
      return src.textContent;
    };
  };

  exports.unsafeSetTextContent = function (value) {
    return function (src) {
      return function () {
        src.textContent = value;
        return {};
      };
    };
  };

  exports.unsafeValue = function (src) {
    return function () {
      return src.value;
    };
  };

  exports.unsafeSetValue = function (value) {
    return function (src) {
      return function () {
        src.value = value;
        return {};
      };
    };
  };

  exports.unsafeContentWindow = function (obj) {
    return function () {
      return obj.contentWindow;
    };
  };

  exports.unsafeClassAdd = function (value) {
    return function (src) {
      return function () {
        src.classList.add(value);
        return {};
      };
    };
  };

  exports.unsafeClassRemove = function (value) {
    return function (src) {
      return function () {
        src.classList.remove(value);
        return {};
      };
    };
  };

  exports.unsafeClassToggle = function (value) {
    return function (src) {
      return function () {
        src.classList.toggle(value);
        return {};
      };
    };
  };

  exports.unsafeClassContains = function (value) {
    return function (src) {
      return function () {
        return src.classList.contains(value);
      };
    };
  };

  exports.unsafeOffsetParent = function (src) {
    return function () {
      return src.offsetParent;
    };
  };

  exports.unsafeOffsetHeight = function (src) {
    return function () {
      return src.offsetHeight;
    };
  };

  exports.unsafeOffsetWidth = function (src) {
    return function () {
      return src.offsetWidth;
    };
  };

  exports.unsafeOffsetTop = function (src) {
    return function () {
      return src.offsetTop;
    };
  };

  exports.unsafeOffsetLeft = function (src) {
    return function () {
      return src.offsetLeft;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Element"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  exports["unsafeOffsetLeft"] = $foreign.unsafeOffsetLeft;
  exports["unsafeOffsetTop"] = $foreign.unsafeOffsetTop;
  exports["unsafeOffsetWidth"] = $foreign.unsafeOffsetWidth;
  exports["unsafeOffsetHeight"] = $foreign.unsafeOffsetHeight;
  exports["unsafeOffsetParent"] = $foreign.unsafeOffsetParent;
  exports["unsafeClassContains"] = $foreign.unsafeClassContains;
  exports["unsafeClassToggle"] = $foreign.unsafeClassToggle;
  exports["unsafeClassRemove"] = $foreign.unsafeClassRemove;
  exports["unsafeClassAdd"] = $foreign.unsafeClassAdd;
  exports["unsafeContentWindow"] = $foreign.unsafeContentWindow;
  exports["unsafeSetValue"] = $foreign.unsafeSetValue;
  exports["unsafeValue"] = $foreign.unsafeValue;
  exports["unsafeSetTextContent"] = $foreign.unsafeSetTextContent;
  exports["unsafeTextContent"] = $foreign.unsafeTextContent;
  exports["unsafeSetInnerHTML"] = $foreign.unsafeSetInnerHTML;
  exports["unsafeInnerHTML"] = $foreign.unsafeInnerHTML;
  exports["unsafeAppendChild"] = $foreign.unsafeAppendChild;
  exports["unsafeChildren"] = $foreign.unsafeChildren;
  exports["unsafeSetStyleAttr"] = $foreign.unsafeSetStyleAttr;
  exports["unsafeGetStyleAttr"] = $foreign.unsafeGetStyleAttr;
  exports["unsafeRemoveAttribute"] = $foreign.unsafeRemoveAttribute;
  exports["unsafeHasAttribute"] = $foreign.unsafeHasAttribute;
  exports["unsafeSetAttribute"] = $foreign.unsafeSetAttribute;
  exports["unsafeGetAttribute"] = $foreign.unsafeGetAttribute;
  exports["unsafeQuerySelectorAll"] = $foreign.unsafeQuerySelectorAll;
  exports["unsafeQuerySelector"] = $foreign.unsafeQuerySelector;
  exports["unsafeGetElementsByName"] = $foreign.unsafeGetElementsByName;
  exports["unsafeGetElementsByClassName"] = $foreign.unsafeGetElementsByClassName;
  exports["unsafeGetElementById"] = $foreign.unsafeGetElementById;;
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];
  var Data_Tuple = PS["Data.Tuple"];     
  var Element = function (appendChild, children, classAdd, classContains, classRemove, classToggle, contentWindow, getAttribute, getElementById, getElementsByClassName, getElementsByName, getStyleAttr, hasAttribute, innerHTML, offsetHeight, offsetLeft, offsetParent, offsetTop, offsetWidth, querySelector, querySelectorAll, removeAttribute, setAttribute, setInnerHTML, setStyleAttr, setTextContent, setValue, textContent, value) {
      this.appendChild = appendChild;
      this.children = children;
      this.classAdd = classAdd;
      this.classContains = classContains;
      this.classRemove = classRemove;
      this.classToggle = classToggle;
      this.contentWindow = contentWindow;
      this.getAttribute = getAttribute;
      this.getElementById = getElementById;
      this.getElementsByClassName = getElementsByClassName;
      this.getElementsByName = getElementsByName;
      this.getStyleAttr = getStyleAttr;
      this.hasAttribute = hasAttribute;
      this.innerHTML = innerHTML;
      this.offsetHeight = offsetHeight;
      this.offsetLeft = offsetLeft;
      this.offsetParent = offsetParent;
      this.offsetTop = offsetTop;
      this.offsetWidth = offsetWidth;
      this.querySelector = querySelector;
      this.querySelectorAll = querySelectorAll;
      this.removeAttribute = removeAttribute;
      this.setAttribute = setAttribute;
      this.setInnerHTML = setInnerHTML;
      this.setStyleAttr = setStyleAttr;
      this.setTextContent = setTextContent;
      this.setValue = setValue;
      this.textContent = textContent;
      this.value = value;
  };
  var value = function (dict) {
      return dict.value;
  };
  var textContent = function (dict) {
      return dict.textContent;
  };
  var setValue = function (dict) {
      return dict.setValue;
  };
  var setTextContent = function (dict) {
      return dict.setTextContent;
  };
  var setStyleAttr = function (dict) {
      return dict.setStyleAttr;
  };
  var setInnerHTML = function (dict) {
      return dict.setInnerHTML;
  };
  var setAttribute = function (dict) {
      return dict.setAttribute;
  };
  var removeAttribute = function (dict) {
      return dict.removeAttribute;
  };
  var querySelectorAll = function (dict) {
      return dict.querySelectorAll;
  };
  var querySelector = function (dict) {
      return dict.querySelector;
  };
  var offsetWidth = function (dict) {
      return dict.offsetWidth;
  };
  var offsetTop = function (dict) {
      return dict.offsetTop;
  };
  var offsetParent = function (dict) {
      return dict.offsetParent;
  };
  var offsetLeft = function (dict) {
      return dict.offsetLeft;
  };
  var offsetHeight = function (dict) {
      return dict.offsetHeight;
  };
  var innerHTML = function (dict) {
      return dict.innerHTML;
  };
  var htmlElement = new Element(Data_DOM_Simple_Unsafe_Element.unsafeAppendChild, Data_DOM_Simple_Unsafe_Element.unsafeChildren, Data_DOM_Simple_Unsafe_Element.unsafeClassAdd, Data_DOM_Simple_Unsafe_Element.unsafeClassContains, Data_DOM_Simple_Unsafe_Element.unsafeClassRemove, Data_DOM_Simple_Unsafe_Element.unsafeClassToggle, Data_DOM_Simple_Unsafe_Element.unsafeContentWindow, Data_DOM_Simple_Unsafe_Element.unsafeGetAttribute, function (id) {
      return function (el) {
          return function __do() {
              var $2 = Data_DOM_Simple_Unsafe_Element.unsafeGetElementById(id)(el)();
              return Data_DOM_Simple_Unsafe_Utils.ensure($2);
          };
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByClassName, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByName, Data_DOM_Simple_Unsafe_Element.unsafeGetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeHasAttribute, Data_DOM_Simple_Unsafe_Element.unsafeInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeOffsetHeight, Data_DOM_Simple_Unsafe_Element.unsafeOffsetLeft, function (el) {
      return function __do() {
          var $3 = Data_DOM_Simple_Unsafe_Element.unsafeOffsetParent(el)();
          return Data_DOM_Simple_Unsafe_Utils.ensure($3);
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeOffsetTop, Data_DOM_Simple_Unsafe_Element.unsafeOffsetWidth, function (sel) {
      return function (el) {
          return function __do() {
              var $4 = Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(sel)(el)();
              return Data_DOM_Simple_Unsafe_Utils.ensure($4);
          };
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeQuerySelectorAll, Data_DOM_Simple_Unsafe_Element.unsafeRemoveAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeSetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent, Data_DOM_Simple_Unsafe_Element.unsafeSetValue, Data_DOM_Simple_Unsafe_Element.unsafeTextContent, Data_DOM_Simple_Unsafe_Element.unsafeValue);
  var hasAttribute = function (dict) {
      return dict.hasAttribute;
  };
  var getStyleAttr = function (dict) {
      return dict.getStyleAttr;
  };
  var getElementsByName = function (dict) {
      return dict.getElementsByName;
  };
  var getElementsByClassName = function (dict) {
      return dict.getElementsByClassName;
  };
  var getElementById = function (dict) {
      return dict.getElementById;
  };
  var getAttribute = function (dict) {
      return dict.getAttribute;
  };                                                     
  var contentWindow = function (dict) {
      return dict.contentWindow;
  };                                                     
  var classToggle = function (dict) {
      return dict.classToggle;
  };
  var classRemove = function (dict) {
      return dict.classRemove;
  };
  var classContains = function (dict) {
      return dict.classContains;
  };
  var classAdd = function (dict) {
      return dict.classAdd;
  };
  var children = function (dict) {
      return dict.children;
  };                                                   
  var appendChild = function (dict) {
      return dict.appendChild;
  };
  exports["Element"] = Element;
  exports["offsetLeft"] = offsetLeft;
  exports["offsetTop"] = offsetTop;
  exports["offsetWidth"] = offsetWidth;
  exports["offsetHeight"] = offsetHeight;
  exports["offsetParent"] = offsetParent;
  exports["classContains"] = classContains;
  exports["classToggle"] = classToggle;
  exports["classAdd"] = classAdd;
  exports["classRemove"] = classRemove;
  exports["contentWindow"] = contentWindow;
  exports["setValue"] = setValue;
  exports["value"] = value;
  exports["setTextContent"] = setTextContent;
  exports["textContent"] = textContent;
  exports["setInnerHTML"] = setInnerHTML;
  exports["innerHTML"] = innerHTML;
  exports["appendChild"] = appendChild;
  exports["children"] = children;
  exports["setStyleAttr"] = setStyleAttr;
  exports["getStyleAttr"] = getStyleAttr;
  exports["removeAttribute"] = removeAttribute;
  exports["hasAttribute"] = hasAttribute;
  exports["setAttribute"] = setAttribute;
  exports["getAttribute"] = getAttribute;
  exports["querySelectorAll"] = querySelectorAll;
  exports["querySelector"] = querySelector;
  exports["getElementsByName"] = getElementsByName;
  exports["getElementsByClassName"] = getElementsByClassName;
  exports["getElementById"] = getElementById;
  exports["htmlElement"] = htmlElement;;
 
})(PS["Data.DOM.Simple.Element"] = PS["Data.DOM.Simple.Element"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Element = PS["Data.DOM.Simple.Element"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Document = PS["Data.DOM.Simple.Unsafe.Document"];
  var htmlDocumentElement = new Data_DOM_Simple_Element.Element(Data_DOM_Simple_Unsafe_Element.unsafeAppendChild, Data_DOM_Simple_Unsafe_Element.unsafeChildren, Data_DOM_Simple_Unsafe_Element.unsafeClassAdd, Data_DOM_Simple_Unsafe_Element.unsafeClassContains, Data_DOM_Simple_Unsafe_Element.unsafeClassRemove, Data_DOM_Simple_Unsafe_Element.unsafeClassToggle, Data_DOM_Simple_Unsafe_Element.unsafeContentWindow, Data_DOM_Simple_Unsafe_Element.unsafeGetAttribute, function (id) {
      return function (el) {
          return function __do() {
              var $0 = Data_DOM_Simple_Unsafe_Element.unsafeGetElementById(id)(el)();
              return Data_DOM_Simple_Unsafe_Utils.ensure($0);
          };
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByClassName, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByName, Data_DOM_Simple_Unsafe_Element.unsafeGetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeHasAttribute, Data_DOM_Simple_Unsafe_Element.unsafeInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeOffsetHeight, Data_DOM_Simple_Unsafe_Element.unsafeOffsetLeft, function (el) {
      return function __do() {
          var $1 = Data_DOM_Simple_Unsafe_Element.unsafeOffsetParent(el)();
          return Data_DOM_Simple_Unsafe_Utils.ensure($1);
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeOffsetTop, Data_DOM_Simple_Unsafe_Element.unsafeOffsetWidth, function (sel) {
      return function (el) {
          return function __do() {
              var $2 = Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(sel)(el)();
              return Data_DOM_Simple_Unsafe_Utils.ensure($2);
          };
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeQuerySelectorAll, Data_DOM_Simple_Unsafe_Element.unsafeRemoveAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeSetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent, Data_DOM_Simple_Unsafe_Element.unsafeSetValue, Data_DOM_Simple_Unsafe_Element.unsafeTextContent, Data_DOM_Simple_Unsafe_Element.unsafeValue);
  exports["htmlDocumentElement"] = htmlDocumentElement;;
 
})(PS["Data.DOM.Simple.Document"] = PS["Data.DOM.Simple.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Window

  exports.unsafeDocument = function (win) {
    return function () {
      return win.document;
    };
  };

  exports.unsafeNavigator = function (win) {
    return function () {
      return win.navigator;
    };
  };

  exports.unsafeLocation = function (win) {
    return function () {
      return win.location;
    };
  };

  exports.unsafeSetTimeout = function (win) {
    return function (delay) {
      return function (func) {
        return function () {
          return win.setTimeout(func, delay);
        };
      };
    };
  };

  exports.unsafeSetInterval = function (win) {
    return function (delay) {
      return function (func) {
        return function () {
          return win.setInterval(func, delay);
        };
      };
    };
  };

  exports.unsafeClearTimeout = function (win) {
    return function (timeout) {
      return function () {
        win.clearTimeout(timeout);
      };
    };
  };

  exports.unsafeInnerWidth = function (win) {
    return function () {
      return win.innerWidth;
    };
  };

  exports.unsafeInnerHeight = function (win) {
    return function () {
      return win.innerHeight;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  exports["unsafeInnerHeight"] = $foreign.unsafeInnerHeight;
  exports["unsafeInnerWidth"] = $foreign.unsafeInnerWidth;
  exports["unsafeClearTimeout"] = $foreign.unsafeClearTimeout;
  exports["unsafeSetInterval"] = $foreign.unsafeSetInterval;
  exports["unsafeSetTimeout"] = $foreign.unsafeSetTimeout;
  exports["unsafeLocation"] = $foreign.unsafeLocation;
  exports["unsafeNavigator"] = $foreign.unsafeNavigator;
  exports["unsafeDocument"] = $foreign.unsafeDocument;;
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module Data.DOM.Simple.Window

  exports.globalWindow = window;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.joinWith = function (s) {
    return function (xs) {
      return xs.join(s);
    };
  };
 
})(PS["Data.String"] = PS["Data.String"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.String"];
  var Prelude = PS["Prelude"];
  var Data_Char = PS["Data.Char"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_String_Unsafe = PS["Data.String.Unsafe"];
  exports["joinWith"] = $foreign.joinWith;;
 
})(PS["Data.String"] = PS["Data.String"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];
  var Data_String = PS["Data.String"];
  var Window = function (clearTimeout, document, innerHeight, innerWidth, location, navigator, setInterval, setTimeout) {
      this.clearTimeout = clearTimeout;
      this.document = document;
      this.innerHeight = innerHeight;
      this.innerWidth = innerWidth;
      this.location = location;
      this.navigator = navigator;
      this.setInterval = setInterval;
      this.setTimeout = setTimeout;
  };
  var setTimeout = function (dict) {
      return dict.setTimeout;
  };
  var setInterval = function (dict) {
      return dict.setInterval;
  };
  var navigator = function (dict) {
      return dict.navigator;
  };
  var location = function (dict) {
      return dict.location;
  };
  var innerWidth = function (dict) {
      return dict.innerWidth;
  };
  var innerHeight = function (dict) {
      return dict.innerHeight;
  };
  var htmlWindow = new Window(Data_DOM_Simple_Unsafe_Window.unsafeClearTimeout, Data_DOM_Simple_Unsafe_Window.unsafeDocument, Data_DOM_Simple_Unsafe_Window.unsafeInnerHeight, Data_DOM_Simple_Unsafe_Window.unsafeInnerWidth, Data_DOM_Simple_Unsafe_Window.unsafeLocation, Data_DOM_Simple_Unsafe_Window.unsafeNavigator, Data_DOM_Simple_Unsafe_Window.unsafeSetInterval, Data_DOM_Simple_Unsafe_Window.unsafeSetTimeout);
  var document = function (dict) {
      return dict.document;
  };
  var clearTimeout = function (dict) {
      return dict.clearTimeout;
  };
  exports["Window"] = Window;
  exports["innerHeight"] = innerHeight;
  exports["innerWidth"] = innerWidth;
  exports["clearTimeout"] = clearTimeout;
  exports["setInterval"] = setInterval;
  exports["setTimeout"] = setTimeout;
  exports["location"] = location;
  exports["navigator"] = navigator;
  exports["document"] = document;
  exports["htmlWindow"] = htmlWindow;
  exports["globalWindow"] = $foreign.globalWindow;;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Array = PS["Data.Array"];
  var Data_String = PS["Data.String"];     
  var RightToLeft = (function () {
      function RightToLeft() {

      };
      RightToLeft.value = new RightToLeft();
      return RightToLeft;
  })();
  var LeftToRight = (function () {
      function LeftToRight() {

      };
      LeftToRight.value = new LeftToRight();
      return LeftToRight;
  })();
  var Star = (function () {
      function Star() {

      };
      Star.value = new Star();
      return Star;
  })();
  var Apple = (function () {
      function Apple() {

      };
      Apple.value = new Apple();
      return Apple;
  })();
  var Tangerine = (function () {
      function Tangerine() {

      };
      Tangerine.value = new Tangerine();
      return Tangerine;
  })();
  var Plum = (function () {
      function Plum() {

      };
      Plum.value = new Plum();
      return Plum;
  })();
  var Decoration = (function () {
      function Decoration(value0) {
          this.value0 = value0;
      };
      Decoration.create = function (value0) {
          return new Decoration(value0);
      };
      return Decoration;
  })();
  var Fur = (function () {
      function Fur(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Fur.create = function (value0) {
          return function (value1) {
              return new Fur(value0, value1);
          };
      };
      return Fur;
  })();
  var elemLength = function (v) {
      if (v instanceof Fur) {
          return v.value1;
      };
      return 1;
  };
  exports["Decoration"] = Decoration;
  exports["Fur"] = Fur;
  exports["RightToLeft"] = RightToLeft;
  exports["LeftToRight"] = LeftToRight;
  exports["Star"] = Star;
  exports["Apple"] = Apple;
  exports["Tangerine"] = Tangerine;
  exports["Plum"] = Plum;
  exports["elemLength"] = elemLength;;
 
})(PS["XmasTree"] = PS["XmasTree"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Random = PS["Control.Monad.Eff.Random"];
  var Data_Array = PS["Data.Array"];
  var Data_Array_Unsafe = PS["Data.Array.Unsafe"];
  var XmasTree = PS["XmasTree"];     
  var rFur_ = function (d) {
      return Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<$>"](Control_Monad_Eff.functorEff)(XmasTree.Fur.create)(d))(Control_Monad_Eff_Random.randomInt(1)(3));
  };
  var choose = function (xs) {
      return Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array_Unsafe.unsafeIndex(xs))(Control_Monad_Eff_Random.randomInt(0)(Data_Array.length(xs) - 1));
  };
  var rDec = Prelude["<$>"](Control_Monad_Eff.functorEff)(XmasTree.Decoration.create)(choose([ XmasTree.Star.value, XmasTree.Apple.value, XmasTree.Tangerine.value, XmasTree.Plum.value ]));
  var rFur = rFur_(choose([ XmasTree.LeftToRight.value, XmasTree.RightToLeft.value ]));
  var rElemsUpToLen = function (m) {
      var go = function (isDecoration) {
          return function (l) {
              if (isDecoration) {
                  return Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.cons)(rDec))(go(false)(l + 1 | 0));
              };
              if (m - l <= 3) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)([ new XmasTree.Fur(XmasTree.RightToLeft.value, m - l) ]);
              };
              if (m - l === 4) {
                  return function __do() {
                      var v = rFur();
                      if (v instanceof XmasTree.Fur) {
                          var n$prime = (function () {
                              var $6 = v.value1 < 3;
                              if ($6) {
                                  return v.value1;
                              };
                              if (!$6) {
                                  return 2;
                              };
                              throw new Error("Failed pattern match at XmasTree.Random line 48, column 15 - line 49, column 11: " + [ $6.constructor.name ]);
                          })();
                          return Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.cons(new XmasTree.Fur(v.value0, n$prime)))(go(true)(l + n$prime | 0))();
                      };
                      throw new Error("Failed pattern match at XmasTree.Random line 37, column 1 - line 38, column 1: " + [ v.constructor.name ]);
                  };
              };
              if (Prelude.otherwise) {
                  return function __do() {
                      var f = rFur();
                      return Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.cons(f))(go(true)(l + XmasTree.elemLength(f) | 0))();
                  };
              };
              throw new Error("Failed pattern match at XmasTree.Random line 37, column 1 - line 38, column 1: " + [ isDecoration.constructor.name, l.constructor.name ]);
          };
      };
      return function __do() {
          var v = rFur_(Prelude.pure(Control_Monad_Eff.applicativeEff)(XmasTree.LeftToRight.value))();
          return Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.cons(v))(go(true)(XmasTree.elemLength(v)))();
      };
  };
  var withHeight = function (v) {
      if (v === 1) {
          return Prelude.pure(Control_Monad_Eff.applicativeEff)([ [ new XmasTree.Decoration(XmasTree.Star.value) ] ]);
      };
      if (v === 2) {
          var r2 = Prelude["<$>"](Control_Monad_Eff.functorEff)(function (x) {
              return [ new XmasTree.Fur(XmasTree.LeftToRight.value, 1), x, new XmasTree.Fur(XmasTree.RightToLeft.value, 1) ];
          })(rDec);
          return Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.snoc)(withHeight(1)))(r2);
      };
      return Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<$>"](Control_Monad_Eff.functorEff)(Data_Array.snoc)(withHeight(v - 1)))(rElemsUpToLen((v * 2 | 0) - 1));
  };
  exports["withHeight"] = withHeight;;
 
})(PS["XmasTree.Random"] = PS["XmasTree.Random"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Data_String = PS["Data.String"];
  var Prelude = PS["Prelude"];
  var XmasTree = PS["XmasTree"];     
  var row = function (xs) {
      return "<div class=\"row\">" + (Data_String.joinWith("")(xs) + "</div>");
  };
  var fromElem = function (e) {
      if (e instanceof XmasTree.Fur && (e.value0 instanceof XmasTree.LeftToRight && e.value1 === 1)) {
          return "<span class=\"fur ltr-1\">&gt;</span>";
      };
      if (e instanceof XmasTree.Fur && (e.value0 instanceof XmasTree.LeftToRight && e.value1 === 2)) {
          return "<span class=\"fur ltr-2\">&gt;&gt;</span>";
      };
      if (e instanceof XmasTree.Fur && e.value0 instanceof XmasTree.LeftToRight) {
          return "<span class=\"fur ltr-3\">&gt;&gt;&gt;</span>";
      };
      if (e instanceof XmasTree.Fur && (e.value0 instanceof XmasTree.RightToLeft && e.value1 === 1)) {
          return "<span class=\"fur rtl-1\">&lt;</span>";
      };
      if (e instanceof XmasTree.Fur && (e.value0 instanceof XmasTree.RightToLeft && e.value1 === 2)) {
          return "<span class=\"fur rtl-2\">&lt;&lt;</span>";
      };
      if (e instanceof XmasTree.Fur && e.value0 instanceof XmasTree.RightToLeft) {
          return "<span class=\"fur rtl-3\">&lt;&lt;&lt;</span>";
      };
      if (e instanceof XmasTree.Decoration && e.value0 instanceof XmasTree.Star) {
          return "<span class=\"decoration star\">*</span>";
      };
      if (e instanceof XmasTree.Decoration && e.value0 instanceof XmasTree.Tangerine) {
          return "<span class=\"decoration tangerine\">o</span>";
      };
      if (e instanceof XmasTree.Decoration && e.value0 instanceof XmasTree.Apple) {
          return "<span class=\"decoration apple\">@</span>";
      };
      if (e instanceof XmasTree.Decoration && e.value0 instanceof XmasTree.Plum) {
          return "<span class=\"decoration plum\">O</span>";
      };
      throw new Error("Failed pattern match at XmasTree.HTML line 15, column 1 - line 16, column 1: " + [ e.constructor.name ]);
  };
  var toHtml = function (t) {
      return "<div class=\"pine\"><div class=\"pine-content\">" + (Data_String.joinWith("")(Prelude.map(Prelude.functorArray)(function ($17) {
          return row(Prelude.map(Prelude.functorArray)(fromElem)($17));
      })(t)) + "</div></div>");
  };
  exports["toHtml"] = toHtml;;
 
})(PS["XmasTree.HTML"] = PS["XmasTree.HTML"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Control_Monad_Eff_Random = PS["Control.Monad.Eff.Random"];
  var Data_Maybe = PS["Data.Maybe"];
  var DOM = PS["DOM"];
  var Data_DOM_Simple_Element = PS["Data.DOM.Simple.Element"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var XmasTree_Random = PS["XmasTree.Random"];
  var XmasTree_HTML = PS["XmasTree.HTML"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];     
  var main = function __do() {
      var v = Data_DOM_Simple_Window.document(Data_DOM_Simple_Window.htmlWindow)(Data_DOM_Simple_Window.globalWindow)();
      var v1 = Data_DOM_Simple_Element.querySelector(Data_DOM_Simple_Document.htmlDocumentElement)("#pine-placeholder")(v)();
      if (v1 instanceof Data_Maybe.Just) {
          var v2 = Prelude["<$>"](Control_Monad_Eff.functorEff)(XmasTree_HTML.toHtml)(XmasTree_Random.withHeight(25))();
          return Data_DOM_Simple_Element.setInnerHTML(Data_DOM_Simple_Element.htmlElement)(v2)(v1.value0)();
      };
      return Control_Monad_Eff_Console.error("Element with id=\"#pine-placeholder\" not found!")();
  };
  exports["main"] = main;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();

},{}]},{},[1]);
